services:
  api:
    build: .
    container_name: crm_backend
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: crm_db
    ports:
      - '5432:5432'
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '8080:80'
    depends_on:
      - postgres
