from enum import Enum

class CodigoRol(Enum):
    ASISTENTE_COMERCIAL = "ASISTENTE_COMERCIAL"
    EJECUTIVO_COMERCIAL = "EJECUTIVO_COMERCIAL"
    EJECUTIVO_SINIESTROS = "EJECUTIVO_SINIESTROS"
    EJECUTIVO_EVALUACION_PROYECTOS = "EJECUTIVO_EVALUACION_PROYECTOS"
    EJECUTIVO_COBRANZA = "EJECUTIVO_COBRANZA"
    EJECUTIVO_RENOVACION = "EJECUTIVO_RENOVACION"
    ASISTENTE_RENOVACION = "ASISTENTE_RENOVACION"