from app.aplicacion.evaluacion_proyectos.use_cases.armar_estudio_comercial_condominio import ArmarEstudioComercialCondominioUseCase


def get_armar_estudio_comercial_use_case():
    return ArmarEstudioComercialCondominioUseCase()